[package]
name = "crowdfund_dapp"
version = "1.0.0"
authors = []

[addresses]
crowdfund_admin = "0xff005f02f214a71afb867ada60e499beab644bcbe66fbd57115bb5cbac38c0b6"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"