[package]
name = "crowdfund_dapp"
version = "1.0.0"
authors = []

[addresses]
crowdfund_admin = "0x81810d53b183eca4645f5bc37fe2cfb3d53af83ed8a6af3b4df7b04f703c8050"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"